name: Pre-commit notebook linting

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  lint:
    name: Notebook linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0